name: Build Windows

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019

    steps:

    - name: Install 7Zip PowerShell Module
      shell: powershell
      run: Install-Module 7Zip4PowerShell -Force -Verbose

    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build
      shell: cmd
      run: call .\windows-build.cmd
    
    - name: Release
      shell: cmd
      run: call .\windows-release.cmd

    - name: Create a github-release on github
      id: create_github_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: xmrig-windows
        release_name: xmrig-windows
        body: ''
        draft: false
        prerelease: false

    - name: Upload release package to github-release
      id: upload-release-package 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_github_release.outputs.upload_url }}
        asset_path: ./build/xmrig-windows.zip
        asset_name: xmrig-windows.zip
        asset_content_type: application/zip
